version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.12
    commands:
      - echo "Installing Snyk CLI..."
      - npm install -g snyk
      - snyk auth ${SNYK_TOKEN}  # Authenticate using the Snyk token
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Preparing for Snyk dependency scanning..."
      # Fail the build if high or critical vulnerabilities are found
      - snyk test --file=requirements.txt --severity-threshold=high
      - echo "Running Snyk code security checks..."
      # Fail the build if high or critical code vulnerabilities are found
      - snyk code test --severity-threshold=high
  post_build:
    commands:
      - echo "Snyk scanning completed."

artifacts:
  discard-paths: no
